pull_request_rules:
  - name: merge automatically when CI passes and PR is approved
    conditions:
      - check-success = "Test 3.10 on macos arm64"
      - check-success = "Test 3.10 on ubuntu aarch64"
      - check-success = "Test 3.10 on ubuntu x86_64"
      - check-success = "Test 3.11 on macos arm64"
      - check-success = "Test 3.11 on ubuntu aarch64"
      - check-success = "Test 3.11 on ubuntu x86_64"
      - check-success = "Test 3.12 on macos arm64"
      - check-success = "Test 3.12 on ubuntu aarch64"
      - check-success = "Test 3.12 on ubuntu x86_64"
      - check-success = "Test 3.13 on macos arm64"
      - check-success = "Test 3.13 on ubuntu aarch64"
      - check-success = "Test 3.13 on ubuntu x86_64"
      - check-success = "Test 3.8 on ubuntu aarch64"
      - check-success = "Test 3.8 on ubuntu x86_64"
      - check-success = "Test 3.9 on macos arm64"
      - check-success = "Test 3.9 on ubuntu aarch64"
      - check-success = "Test 3.9 on ubuntu x86_64"
      - check-success = "pre-commit.ci - pr"
      - or:
        - approved-reviews-by = nim65s
        - author = nim65s
        - author = dependabot[bot]
        - author = github-actions[bot]
        - author = pre-commit-ci[bot]
    actions:
      merge:
