name: Tests

on:
  push:
  schedule:
    - cron: "29 4 * * 0,3"

jobs:
  test:
    name: "Test ${{ matrix.py }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
        py: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - run: python -m pip install crocoddyl tsid ndcurves
        env:
          PYTHONWARNINGS: error
      - run: python test.py
