name: Tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "29 4 * * 0,3"

jobs:
  test:
    name: "Test ${{ matrix.python }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm", "macos-13", "macos-14"]
        python: ["cp38", "cp39", "cp310", "cp311", "cp312", "cp313"]
        exclude:
          - os: "macos-14"
            python: "cp38"

    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ matrix.python }}" | sed "s/cp3/PYTHON_VERSION=3./" >> "${GITHUB_ENV}"
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: python -m pip install eigenpy coal-library pin crocoddyl tsid ndcurves
      - run: python test.py
        #env:
          #PYTHONWARNINGS: error
